name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  Build-and-unit-test:
    name: Build and unit test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint ./src --max-warnings 0

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

      - uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

  E2E-tests:
    needs: Build-and-unit-test

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    name: E2E tests in ${{ matrix.browser }}

    env:
      EMAIL_HOST: localhost
      EMAIL_PORT: 2525
      EMAIL_SENDER_NAME: Read Receipt
      EMAIL_SENDER_EMAIL: read.receipt@tobythe.dev
      EMAIL_USER: user
      EMAIL_PASS: pass
      DEV_IP: 95.150.202.188

    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Run E2E Tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          install-command: npm ci
          build: npm run build
          start: npm run start:e2e
          wait-on: http://localhost:3000
