name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  Build-and-unit-test:
    name: Build and unit test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint ./src --max-warnings 0

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:ci

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

      - uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

  E2E-tests:
    needs: Build-and-unit-test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chrome, firefox]

    name: E2E tests on ${{ matrix.os }} in ${{ matrix.browser }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run E2E Tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          headless: true
          start: npm run start:e2e
          wait-on: http://localhost:3000
